<a href="https://colab.research.google.com/github/Diyorbek788/API/blob/main/NumpyAssignment_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


1-Topshiriq

In [ ]:
!wget -O GM_Cars.zip "https://drive.google.com/uc?export=download&id=1i57sWZxVA9Xh64eVvyInkIJmKT-4WTz" && unzip GM_Cars.zip && rm -r GM_Cars.zip

--2026-03-11 09:35:06--  https://drive.google.com/uc?export=download&id=1i57sWZxVA9Xh64eVvyInkIJmKT-4WTz
Resolving drive.google.com (drive.google.com)... 192.178.210.113, 192.178.210.102, 192.178.210.101, ...
Connecting to drive.google.com (drive.google.com)|192.178.210.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1i57sWZxVA9Xh64eVvyInkIJmKT-4WTz&export=download [following]
--2026-03-11 09:35:06--  https://drive.usercontent.google.com/download?id=1i57sWZxVA9Xh64eVvyInkIJmKT-4WTz&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 192.178.209.132, 2607:f8b0:4001:c70::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|192.178.209.132|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2026-03-11 09:35:06 ERROR 404: Not Found.



In [ ]:
!unzip GM_Cars.zip

Archive:  GM_Cars.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of GM_Cars.zip or
        GM_Cars.zip.zip, and cannot find GM_Cars.zip.ZIP, period.


In [5]:
!wget -O GM_Cars.zip "https://drive.google.com/uc?export=download&id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy" && unzip GM_Cars.zip && rm -r GM_Cars.zip

--2026-03-11 09:37:43--  https://drive.google.com/uc?export=download&id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy
Resolving drive.google.com (drive.google.com)... 192.178.210.138, 192.178.210.139, 192.178.210.101, ...
Connecting to drive.google.com (drive.google.com)|192.178.210.138|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy&export=download [following]
--2026-03-11 09:37:43--  https://drive.usercontent.google.com/download?id=1i57swZxVA9Xh64eVvylnkIJmKT-4WTZy&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 192.178.209.132, 2607:f8b0:4001:c70::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|192.178.209.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 793 [application/octet-stream]
Saving to: ‘GM_Cars.zip’

GM_Cars.zip         100%[===================>]     793  --.-KB/s    in 0

In [15]:
data1 = np.load('GM_Cars/gm_2020.npz')

In [16]:
data2 = np.load('GM_Cars/gm_2021.npz')

In [17]:
models = data1['models']
qnts = data1['qnts']

In [18]:
models

array(['Labo', 'Damas', 'Spark', 'Nexia', 'Cobalt', 'Gentra'], dtype='<U6')

In [19]:
qnts

array([ 4521, 30889, 16370, 41663, 44901, 30368], dtype=int32)

2-Topshiriq



In [23]:
import numpy as np

q1 = np.load('GM_Cars/gm_2020.npz')['qnts']
q2 = np.load('GM_Cars/gm_2021.npz')['qnts']


In [24]:
q1.sum(), q2.sum()

(np.int64(168712), np.int64(124734))

3-Topshiriq

In [25]:
data1 = np.load('GM_Cars/gm_2020.npz')
data2 = np.load('GM_Cars/gm_2021.npz')

models1 = data1['models']
qnts1 = data1['qnts']

models2 = data2['models']
qnts2 = data2['qnts']

mask1 = (models1=='Damas') | (models1=='Nexia') | (models1=='Cobalt') | (models1=='Gentra')
mask2 = (models2=='Damas') | (models2=='Nexia') | (models2=='Cobalt') | (models2=='Gentra')

qnts1[mask1], qnts2[mask2]

(array([30889, 41663, 44901, 30368], dtype=int32),
 array([33682, 14442, 36317, 26266], dtype=int32))

4-Topshiriq

In [26]:
selected1 = qnts1[mask1]
selected2 = qnts2[mask2]

(selected1 / qnts1.sum()) * 100, (selected2 / qnts2.sum()) * 100

(array([18.30871544, 24.69474608, 26.61399308, 17.99990516]),
 array([27.00306252, 11.57823849, 29.11555791, 21.0576106 ]))